batch_size: 64
beta: 1
epochs: 600
exp_name: iwae_text_bs_1level2
labels: null
loss: bce
lr: 1e-4
mixing: htvae
modality_1:
  decoder: TxtTransformer
  encoder: TxtTransformer
  feature_dim:
  - 52
  - 27
  - 1
  mod_type: text
  path: ./data/level2_full/attrs.pkl
model_specific:
  multi_nets: 0
  output_mean: 0
  single_joint: 0
  t_ff: 1024
  t_heads: 2
  t_layers: 8
  zero_masking: 0
n_latents: 64
obj: iwae
optimizer: adam
pre_trained: null
seed: 2
test_split: 0.1
viz_freq: 20
