batch_size: 64
beta: 1
epochs: 600
exp_name: elbo_image_bs_2level2
labels: null
loss: bce
lr: 1e-4
mixing: htvae
modality_1:
  encoder: CNN                # name of the encoder class
  decoder: CNN                # name of the decoder class
  feature_dim: [64, 64, 3]    # dimensionality of the data (e.g. 64,64,3 for images)
  mod_type: image             # how to treat the modality (image/text/action)
  path: ./data/level2_full/image
model_specific:
  multi_nets: 0
  output_mean: 0
  single_joint: 0
  t_ff: 1024
  t_heads: 2
  t_layers: 8
  zero_masking: 0
n_latents: 64
obj: elbo
optimizer: adam
pre_trained: null
seed: 2
test_split: 0.1
viz_freq: 20
