batch_size: 32
epochs: 600
dataset_name: gebid
exp_name: gebidlevel3_mmvae_31
labels: null
beta: 1
lr: 1e-4
mixing: moe
modality_1:
  decoder: CNN
  encoder: CNN
  mod_type: image
  recon_loss: lprob
  path: ./data/level3/image
modality_2:
  decoder: TxtTransformer
  encoder: TxtTransformer
  mod_type: text
  recon_loss: category_ce
  path: ./data/level3/attrs.pkl
n_latents: 64
obj: elbo
optimizer: adam
pre_trained: null
seed: 2
test_split: 0.1
viz_freq: 20
