general:
  n_epochs: 500
  n_latents: 8
  obj: moe_elbo
  loss: lprob
  viz_freq: 100
  model: 2mods
  noisy_txt: False
modality_1:
  dataset: ../data/image
  type: img
modality_2:
  dataset: ../data/attrs.pkl
  type: txt





