name: multivae
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - cudatoolkit>=10.2
  - torchaudio
  - pillow
  - pyparsing
  - pyqt
  - h5py
  - python=3.8
  - pip
  - chainer
  - click
  - colorama
  - commentjson
  - configparser
  - gensim
  - matplotlib
  - mpmath
  - nltk
  - numba
  - numpy
  - pandas
  - pickleshare
  - protobuf
  - pydub
  - pywavelets
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - wget
  - tarfile
  - pytorch
  - tensorboard
  - torchvision
  - pytorch-lightning==1.7.7
  - umap-learn
  - pyyaml
  - pytest
  - pip:
    - adabelief-pytorch
    - colorthief
    - opencv-python
    - pixyz
    - pyttsx3
    - torchnet
