batch_size: 32
epochs: 600
exp_name: gebidlevel2_mmvae_3
labels: null
loss: bce
lr: 1e-4
mixing: moe
modality_1:
  decoder: CNN
  encoder: CNN
  mod_type: image
  path: ./data/level2/image
modality_2:
  decoder: TxtTransformer
  encoder: TxtTransformer
  mod_type: text
  path: ./data/level2/attrs.pkl
n_latents: 16
obj: elbo
optimizer: adam
pre_trained: null
seed: 4
test_split: 0.1
viz_freq: 20
