batch_size: 64
epochs: 800
exp_name: htvae_level5_0110_bs_2
labels: null
loss: bce
lr: 1e-4
mixing: htvae
modality_1:
  decoder: CNN
  encoder: CNN
  feature_dim:
  - 64
  - 64
  - 3
  mod_type: image
  path: ./data/level5/image
modality_2:
  decoder: TxtTransformer
  encoder: TxtTransformer
  feature_dim:
  - 52
  - 27
  - 1
  mod_type: text
  path: ./data/level5/attrs.pkl
model_specific:
  multi_nets: 0
  output_mean: 1
  single_joint: 1
  zero_masking: 0
n_latents: 128
obj: elbo
optimizer: adam
pre_trained: null
seed: 2
test_split: 0.1
viz_freq: 20
