batch_size: 32
epochs: 600
exp_name: gebidlevel4_mvae_18
labels: null
loss: bce
lr: 1e-4
mixing: poe
modality_1:
  decoder: CNN
  encoder: CNN
  feature_dim:
  - 64
  - 64
  - 3
  mod_type: image
  path: ./data/level4/image
modality_2:
  decoder: TxtTransformer
  encoder: TxtTransformer
  feature_dim:
  - 52
  - 27
  - 1
  mod_type: text
  path: ./data/level4/attrs.pkl
n_latents: 128
obj: elbo
optimizer: adam
pre_trained: null
seed: 4
test_split: 0.1
viz_freq: 20
