batch_size: 32
epochs: 600
dataset_name: gebid
exp_name: gebidlevel4_mvae_15
labels: null
beta: 1
lr: 1e-4
mixing: poe
modality_1:
  decoder: CNN
  encoder: CNN
  mod_type: image
  recon_loss:  bce
  path: ./data/level4/image
modality_2:
  decoder: TxtTransformer
  encoder: TxtTransformer
  mod_type: text
  recon_loss: category_ce
  path: ./data/level4/attrs.pkl
n_latents: 128
obj: elbo
optimizer: adam
pre_trained: null
seed: 1
test_split: 0.1
viz_freq: 20
