batch_size: 32
epochs: 1000
exp_name: configs_latent_dim_moe_1
labels: null
loss: bce
lr: 1e-4
mixing: moe
modality_1:
  decoder: CNN
  encoder: CNN
  feature_dim:
  - 64
  - 64
  - 3
  path: /home/gabi/mirracle_remote/mirracle_multimodal/mirracle_multimodal/data/image
modality_2:
  decoder: TxtTransformer
  encoder: TxtTransformer
  feature_dim:
  - 52
  - 27
  - 1
  path: /home/gabi/mirracle_remote/mirracle_multimodal/mirracle_multimodal/data/attrs.pkl
n_latents: 32
obj: elbo
optimizer: adam
pre_trained: null
seed: 2
viz_freq: 1
