batch_size: 64
epochs: 500
exp_name: configs_latent_dim_poe_4
labels: null
loss: l1
lr: 1e-3
mixing: poe
modality_1:
  decoder: TxtTransformer
  encoder: TxtTransformer
  feature_dim:
  - 52
  - 27
  - 1
  path: /home/sejnogab/mirracle_multimodal/mirracle_multimodal/data/attrs.pkl
modality_2:
  decoder: CNN
  encoder: CNN
  feature_dim:
  - 64
  - 64
  - 3
  path: /home/sejnogab/mirracle_multimodal/mirracle_multimodal/data/image
n_latents: 16
obj: elbo
optimizer: adam
pre_trained: null
seed: 2
viz_freq: 2
