batch_size: 32
epochs: 600
dataset_name: gebid
exp_name: gebidlevel2_mmvae_9
labels: null
beta: 1
lr: 1e-4
mixing: moe
modality_1:
  decoder: CNN
  encoder: CNN
  mod_type: image
  recon_loss:  bce
  path: ./data/level2/image
modality_2:
  decoder: TxtTransformer
  encoder: TxtTransformer
  mod_type: text
  recon_loss: category_ce
  path: ./data/level2/attrs.pkl
n_latents: 32
obj: elbo
optimizer: adam
pre_trained: null
seed: 5
test_split: 0.1
viz_freq: 20
