batch_size: 32
epochs: 600
exp_name: gebidlevel2_mvae_39
labels: null
loss: lprob
lr: 1e-4
mixing: poe
modality_1:
  decoder: CNN
  encoder: CNN
  mod_type: image
  path: ./data/level2/image
modality_2:
  decoder: TxtTransformer
  encoder: TxtTransformer
  mod_type: text
  path: ./data/level2/attrs.pkl
n_latents: 128
obj: elbo
optimizer: adam
pre_trained: null
seed: 5
test_split: 0.1
viz_freq: 20
