batch_size: 32
epochs: 600
dataset_name: gebid
exp_name: gebidlevel1_mmvae_36
labels: null
beta: 1
path: ./data/level1/image
modality_2:
  decoder: TxtTransformer
  encoder: TxtTransformer
  mod_type: text
  recon_loss: category_ce
  path: ./data/level1/attrs.pkl
n_latents: 128
obj: elbo
optimizer: adam
pre_trained: null
seed: 2
test_split: 0.1
viz_freq: 20
