batch_size: 32
epochs: 600
exp_name: gebidlevel5_mmvae_13
labels: null
beta: 1
lr: 1e-4
mixing: moe
modality_1:
  decoder: CNN
  encoder: CNN
  mod_type: image
  recon_loss:  bce
  path: ./data/level5/image
modality_2:
  decoder: TxtTransformer
  encoder: TxtTransformer
  mod_type: text
  recon_loss: category_ce
  path: ./data/level5/attrs.pkl
n_latents: 64
obj: elbo
optimizer: adam
pre_trained: null
seed: 4
test_split: 0.1
viz_freq: 20
