batch_size: 24
beta: 1
dataset_name: cdspritesplus
epochs: 150
exp_name: moe_level1_1
iterseeds: 5
labels: null
lr: 1e-4
mixing: moe
modality_1:
  decoder: CNN
  encoder: CNN
  mod_type: image
  prior: normal
  path: ./data/CdSpritesplus/level1/traindata.h5
  private_latents: 10
  recon_loss: bce
modality_2:
  decoder: TxtTransformer
  encoder: TxtTransformer
  mod_type: text
  prior: normal
  path: ./data/CdSpritesplus/level1/traindata.h5
  private_latents: 10
  recon_loss: category_ce
n_latents: 24
obj: elbo
optimizer: adam
pre_trained: null
seed: 1
test_split: 0.1
viz_freq: 10
