batch_size: 24
beta: 1
dataset_name: cdspritesplus
epochs: 250
exp_name: mopoe
iterseeds: 5
labels: null
lr: 1e-4
mixing: mopoe
modality_1:
  decoder: CNN
  encoder: CNN
  prior: normal
  mod_type: image
  private_latents: 10
  path: ./data/CdSpritesplus/level5/traindata.h5
  recon_loss: bce
modality_2:
  decoder: TxtTransformer
  encoder: TxtTransformer
  mod_type: text
  prior: normal
  private_latents: 10
  path: ./data/CdSpritesplus/level5/traindata.h5
  recon_loss: category_ce
n_latents: 24
obj: elbo
optimizer: adam
pre_trained: null
seed: 1
test_split: 0.1
viz_freq: 10