batch_size: 16
epochs: 600
exp_name: cub
labels:
loss: bce
lr: 1e-3
mixing: moe
n_latents: 16
obj: elbo
optimizer: adam
pre_trained: null
seed: 2
viz_freq: 1
test_split: 0.1
dataset_name: cub
modality_1:
  decoder: CNN
  encoder: CNN
  mod_type: image
  path: ./data/cub/images
modality_2:
  decoder: TxtTransformer
  encoder: TxtTransformer
  mod_type: text
  path: ./data/cub/cub_captions.pkl
