batch_size: 32
epochs: 600
exp_name: test
labels: null
loss: bce
lr: 1e-4
mixing: moe
n_latents: 64
obj: elbo
optimizer: adam
pre_trained: null
seed: 2
viz_freq: 20
test_split: 0.1
modality_1:
  decoder: CNN
  encoder: CNN
  feature_dim: [64, 64, 3]
  mod_type: image
  path: ./data/level5/image
modality_2:
  decoder: TxtTransformer
  encoder: TxtTransformer
  feature_dim: [52, 27, 1]
  mod_type: text
  path: ./data/level5/attrs.pkl

