batch_size: 128
epochs: 600
exp_name: mnistsvhn2
labels:
lr: 1e-3
mixing: moe
iterseeds: 1
n_latents: 20
obj: dreg
optimizer: adam
pre_trained: null
seed: 1
beta: 1
K: 30
viz_freq: 1
test_split: 0.1
dataset_name: mnist_svhn
modality_1:
  decoder: MNIST
  encoder: MNIST
  prior: laplace
  mod_type: mnist
  recon_loss: lprob
  path: ./data/mnist_svhn/train-ms-mnist-idx.pt
modality_2:
  decoder: SVHN
  encoder: SVHN
  mod_type: svhn
  prior: laplace
  recon_loss: lprob
  path: ./data/mnist_svhn/train-ms-svhn-idx.pt
