batch_size: 32
epochs: 600
exp_name: cub
labels:
beta: 1
lr: 1e-3
mixing: moe
n_latents: 16
obj: elbo
optimizer: adam
pre_trained: null
seed: 2
viz_freq: 10
test_split: 0.1
dataset_name: cub
modality_1:
  decoder: CNN
  encoder: CNN
  mod_type: image
  recon_loss:  bce
  path: ./data/cub/images
modality_2:
  decoder: TxtTransformer
  encoder: TxtTransformer
  mod_type: text
  recon_loss: category_ce
  path: ./data/cub/cub_captions.pkl
