batch_size: 32
epochs: 600
exp_name: fashionmnist
labels:
lr: 1e-3
mixing: poe
iterseeds: 1
n_latents: 32
obj: elbo
optimizer: adam
pre_trained: null
seed: 2
beta: 1
viz_freq: 1
test_split: 0.1
dataset_name: fashionmnist
modality_1:
  decoder: MNIST
  encoder: MNIST
  mod_type: image
  recon_loss:  bce
  path:
modality_2:
  decoder: FNN
  encoder: FNN
  mod_type: label
  recon_loss:  category_ce
  path: