batch_size: 32
epochs: 2
exp_name: test
labels: null
loss: bce
lr: 1e-4
mixing: moe
n_latents: 64
obj: elbo
optimizer: adam
pre_trained: null
seed: 2
viz_freq: 20
test_split: 0.1
dataset_name: gebid
modality_1:
  decoder: CNN
  encoder: CNN
  mod_type: image
  path: ./data/level2/image
modality_2:
  decoder: TxtTransformer
  encoder: TxtTransformer
  mod_type: text
  path: ./data/level2/attrs.pkl

