batch_size: 32
epochs: 600
exp_name: mnistsvhn
labels: ./data/mnist_svhn/labels.pkl
loss: bce
lr: 1e-3
mixing: moe
n_latents: 16
obj: elbo
optimizer: adam
pre_trained: null
seed: 2
viz_freq: 10
test_split: 0.1
modality_1:
  decoder: MNIST
  encoder: MNIST
  feature_dim: [28,28,1]
  mod_type: image
  path: ./data/mnist_svhn/mnist
modality_2:
  decoder: SVHN
  encoder: SVHN
  feature_dim: [32,32,3]
  mod_type: image
  path: ./data/mnist_svhn/svhn
