batch_size: 32
epochs: 20
exp_name: poe
labels:
beta: 1
lr: 1e-4
mixing: poe
n_latents: 64
obj: elbo
optimizer: adam
pre_trained: null
seed: 2
viz_freq: 1
test_split: 0.1
dataset_name: mnist_svhn
modality_1:
  decoder: MNIST
  encoder: MNIST
  mod_type: mnist
  recon_loss:  bce
  path: ./data/mnist_svhn/mnist
modality_2:
  decoder: SVHN
  encoder: SVHN
  recon_loss: bce
  mod_type: svhn
  path: ./data/mnist_svhn/svhn

