batch_size: 64                # batch size
n_latents:  16              # latent space dimensionality
epochs: 500                   # number of trainin epochs
exp_name: mnistelbo           # folder name to save results
labels: /home/gabi/mirracle_multimodal/multimodal_compare/data/mnist_svhn/labels.pkl   # (optional) path to data labels for t-SNE
loss: lprob                     # reconstruction loss (bce/l1/mse/lprob/category)
lr: 1e-4                      # learning rate
mixing: htvae                 # multimodal mixing (poe/moe/mopoe)
model_specific:
  zero_masking: 0
  output_mean:  0
  single_joint: 0
  multi_nets: 0
  t_layers: 8
  t_heads: 2
  t_ff: 1024
obj: elbo                    # objective (currently only elbo)
optimizer: adam               # optimizer (adam/adabelief)
pre_trained: null             # (optional) path to pre-trained weights
seed: 2                       # seed number
beta: 1
test_split: 0.1               # proportion of data to use for testset
viz_freq: 20                   # visualize results after each N epochs
modality_1:
  decoder: MNIST
  encoder: MNIST
  feature_dim: [28,28,1]
  mod_type: image
  path: ./data/mnist_svhn/mnist
