batch_size: 64                # batch size
n_latents: 32                 # latent space dimensionality
epochs: 800                   # number of trainin epochs
exp_name: htvae_tranparams_06             # folder name to save results
labels: null                  # (optional) path to data labels for t-SNE
loss: bce                     # reconstruction loss (bce/l1/mse/lprob/category)
lr: 1e-4                      # learning rate
mixing: htvae                 # multimodal mixing (poe/moe/mopoe)
model_specific:
  zero_masking: 0
  output_mean:  0
  single_joint: 0
  multi_nets: 0
  t_layers: 8
  t_heads: 4
  t_ff: 1024
obj: elbo                     # objective (currently only elbo)
optimizer: adam               # optimizer (adam/adabelief)
pre_trained: null             # (optional) path to pre-trained weights
seed: 2                       # seed number
beta: 4
test_split: 0.1               # proportion of data to use for testset
viz_freq: 10                   # visualize results after each N epochs
modality_1:                   # define first modality
  encoder: CNN                # name of the encoder class
  decoder: CNN                # name of the decoder class
  feature_dim: [64, 64, 3]    # dimensionality of the data (e.g. 64,64,3 for images)
  mod_type: image             # how to treat the modality (image/text/action)
  path: ./data/level3res/image   # path to data
modality_2:                   # define second modality
  decoder: TxtTransformer
  encoder: TxtTransformer
  feature_dim: [52, 27, 1]
  mod_type: text
  path: ./data/level3res/attrs.pkl
