batch_size: 64
epochs: 800
exp_name: poe_level3res_bs_0
labels: null
loss: bce
lr: 1e-4
mixing: poe
modality_1:
  decoder: CNN
  encoder: CNN
  feature_dim:
  - 64
  - 64
  - 3
  mod_type: image
  path: ./data/level3res/image
modality_2:
  decoder: TxtTransformer
  encoder: TxtTransformer
  feature_dim:
  - 52
  - 27
  - 1
  mod_type: text
  path: ./data/level3res/attrs.pkl
n_latents: 16
obj: elbo
optimizer: adam
pre_trained: null
seed: 2
test_split: 0.1
viz_freq: 20
