n_latents: 32
batch_size: 64
epochs: 2000
obj: elbo
loss: lprob
viz_freq: 50
mixing: moe
exp_name: sounds_actions
pre_trained:
seed: 2
modality_1:
   encoder: Audio
   decoder: Audio
   path: /home/gabi/kubecova-action-representationvae/dataset1/sounds.pkl
   feature_dim: [56057,2]
modality_2:
   encoder: Transformer
   decoder: Transformer
   path: /home/gabi/kubecova-action-representationvae/dataset1/action_data.pkl
   feature_dim: [60,1,24]



