  n_latents: 64
  batch_size: 64
  epochs: 500
  obj: elbo
  loss: bce
  viz_freq: 20
  mixing: moe
  exp_name: exp_01
  pre_trained:
  seed: 2
  modality_1:
   encoder: CNN
   decoder: CNN
   path: ../data/image
   feature_dim: [64,64,3]
  modality_2:
    encoder: FCNN
    decoder: FCNN
    path:  ../data/3d.pkl
    feature_dim: [3, 3]



