[general]
  n_latents: 12
  obj: elbo
  loss: bce
  viz_freq: 100
  mixing: poe
  modalities_num: 1
  exp_name: incremental_3000_directmixing_5
  pre_trained:
  llik_scaling: 0
  buffer: 999
  batch_size: 64
  data_repeats: 500
  replay_samples_percent: 5
  direct_sample_mixing: true
  sample_replay: false
  seed: 2
  mod_type: img
  mod_testdata: ./data/image_test
  mod_path: ./data/image_3000
  mod_datadim: 12288
  mod2_datadim:
  mod2_type:
  mod2_numwords:
  mod3_type:
  mod4_type:
  mod5_type:
  mod6_type:






