  n_latents: 12
  batch_size: 64
  epochs: 500
  obj: elbo
  loss: bce
  viz_freq: 20
  mixing:
  exp_name: exp_01
  pre_trained:
  seed: 2
  modality_1:
   encoder: CNN
   decoder: CNN
   path: ../data/image
   feature_dim: [64,64,3]


