[general]
  n_latents: 12
  batch_size: 64
  epochs: 500
  obj: elbo
  loss: bce
  viz_freq: 20
  mixing: poe
  modalities_num: 2
  exp_name: exp_02
  pre_trained:
  llik_scaling: 0
  seed: 2
  mod1_type: img
  mod1_path: ../data/image
  mod1_datadim: 12288
  mod2_path: ../data/4096d.pkl
  mod2_datadim: 12288
  mod2_type: txt
  mod2_numwords: 3
  mod3_type:
  mod4_type:
  mod5_type:
  mod6_type:



