[general]
  n_latents: 8
  obj: elbo
  loss: bce
  viz_freq: 500
  mixing: poe
  modalities_num: 1
  exp_name: incrtest3
  pre_trained:
  llik_scaling: 0
  buffer: 1000
  batch_size: 32
  data_repeats: 500
  seed: 2
  mod_type: img
  mod_testdata: ../data/testset
  mod_path: ../data/image
  mod_datadim: 12288
  mod2_datadim:
  mod2_type:
  mod2_numwords:
  mod3_type:
  mod4_type:
  mod5_type:
  mod6_type:






