[general]
  n_latents: 24
  batch_size: 64
  epochs: 500
  obj: elbo
  loss: bce
  viz_freq: 50
  mixing: poe
  modalities_num: 1
  exp_name: incretest
  pre_trained:
  llik_scaling: 0
  seed: 1
  mod_type: img
  mod_path: ../data/image
  mod_datadim: 12288
  mod2_path:
  mod2_datadim:
  mod2_type:
  mod2_numwords:
  mod3_type:
  mod4_type:
  mod5_type:
  mod6_type:



