[general]
  n_latents: 12
  batch_size: 64
  epochs: 500
  obj: elbo
  loss: bce
  viz_freq: 50
  mixing: poe
  modalities_num: 1
  exp_name: nonincre_allatonce_3000_shuffled
  pre_trained:
  llik_scaling: 0
  seed: 2
  mod_type: img
  mod_testdata: ./data/image_test
  mod_path: ./data/image_3000
  mod_datadim: 12288
  mod2_path:
  mod2_datadim:
  mod2_type:
  mod2_numwords:
  mod3_type:
  mod4_type:
  mod5_type:
  mod6_type:



