batch_size: 32
epochs: 600
exp_name: batch_size_exp_bs_12
labels: null
loss: bce
lr: 1e-4
mixing: moe
modality_1:
  decoder: CNN
  encoder: CNN
  feature_dim:
  - 64
  - 64
  - 3
  mod_type: image_png
  path: ./data/level5/image
modality_2:
  decoder: TxtTransformer
  encoder: TxtTransformer
  feature_dim:
  - 52
  - 27
  - 1
  mod_type: text_str
  path: ./data/level5/attrs.pkl
n_latents: 64
obj: elbo
optimizer: adam
pre_trained: null
seed: 2
viz_freq: 20
