batch_size: 32
epochs: 600
exp_name: gebidlevel1_mmvae_26
labels: null
loss: lprob
lr: 1e-4
mixing: moe
modality_1:
  decoder: CNN
  encoder: CNN
  mod_type: image
  path: ./data/level1/image
modality_2:
  decoder: TxtTransformer
  encoder: TxtTransformer
  mod_type: text
  path: ./data/level1/attrs.pkl
n_latents: 32
obj: elbo
optimizer: adam
pre_trained: null
seed: 2
test_split: 0.1
viz_freq: 20
